[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_swap = "52GXhYuU4P4mfcJnvuuhdhfEPfooE8khK4PmcZg7XaFM"

[programs.devnet]
token_swap = "52GXhYuU4P4mfcJnvuuhdhfEPfooE8khK4PmcZg7XaFM"


[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
wallet = "/Users/eason/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
