[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_spl_amm = "5pCZ4MZ1BU4FSx7zWxCtAQ5vyhxWLikoZpLV6biPG8Rj"

[programs.devnet]
anchor_spl_amm = "5pCZ4MZ1BU4FSx7zWxCtAQ5vyhxWLikoZpLV6biPG8Rj"


[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
wallet = "/Users/eason/.config/solana/id.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "genesis/metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
